version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  postgres:
    image: postgres:16.6
    container_name: postgres
    environment:
      POSTGRES_USER: tbank
      POSTGRES_PASSWORD: admin-19344-1023982
      POSTGRES_DB: PROD
    ports:
      - "8032:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "8090:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SERVER_ROOT_URL: https://prod-team-19-n7cvsvtm.REDACTED/grafana
      GF_SECURITY_ALLOW_EMBEDDING: true
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - postgres
    restart: unless-stopped

  backend:
    image: "${IMAGE_NAME}"
    container_name: backend
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: postgresql+psycopg://tbank:admin-19344-1023982@postgres:5432/PROD
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      BUCKET_NAME: campaign-images
      REGION_NAME: us-east-1
    depends_on:
      - minio
      - postgres
    restart: unless-stopped

volumes:
  minio_data:
  postgres_data:
  grafana_data: